### ISSUE TITLE
Document How Graphics Coordinates Work

### ISSUE THREAD

**Issue by oldpatientsea** [oldpatientsea/agon-bbc-basic-manual#22]
BBC Basic uses pixel coordinates that run from 0 to 1280 left-to-right and from 0 to 1204 bottom to top. 

This is used by PLOT commands to draw points, lines and triangles. Historically on the BBC micro, the logical coordinates meant that you could draw a triangle in the high resolution 2 colour mode, through to the low resolution 16 colour mode and it would appear in the correct position on screen despite the physical resolution being different. 

But there is a mode in which you have the normal (non-BBC Basic, non-scaled) PLOT coordinates, evoked by calling

```VDU 23,0,192,0```

Clarify how sprite/bitmap coordinates work too.

**Comment by stevesims** [comment]
I have been considering changing OS coordinates...  much as Acorn themselves did on the Archimedes...

Acorn picked 1280x1024 because those dimensions could be reached with integer multipliers for all the physical screen modes.  _none_ of the screen modes we have give an integer multiplier to 1024.  this makes writing code that uses OS coordinates with the hope of getting consistent spacing between points pretty much impossible.  This makes the OS coordinate system less useful than it should be on the Agon, so many devs end up switching to the non-scaled coordinate system.

When Acorn made the Archimedes they kept compatibility with the Beeb as much as they could, but they stuck with integer multipliers for OS units (either 2 or 4) for their new screen modes.  Their rough heuristic seems to have been to use integer multipliers that result in an OS resolution of at least 1280x800.  (There's just _one_ exception to that rule.)

Given the resolutions we have, I'd be inclined to follow their heuristic which would also give us OS resolutions of at least 1280x800.  Most of our modes would end up as 1280x960.

I'd include in this a "compatibility" mode that used blanket 1280x1024 for all modes.

**Comment by oldpatientsea** [comment]
Thanks Steve. I'm swamped at the moment but keeping an eye on github emails although this is the first moment I've had free to respond. 

Once there's a stable Quark release I'll allocate some time to getting the documentation up to date so I'll keep an eye out for your proposed changes along with everything else (you've been busy, I see and made some great contributions!). I will seek you out for more info here or on the Discord with any inevitable further questions.

**Comment by oldpatientsea** [comment]
Sorry but I no longer have time to maintain this and am archiving the repository. Please feel free to fork and make any adjustments there.
